/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cryptohelper.view;

import cryptohelper.controller.SessionController;
import cryptohelper.model.Sessione;
import cryptohelper.model.Soluzione;
import cryptohelper.model.UserInfo;
import java.sql.SQLException;
import java.util.List;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author Mattia Cerrato, mattia.cerrato[at]studenti.unito[dot]it
 */
public class CaricaSoluzioneDialog extends javax.swing.JDialog {

    /**
     * A return status code - returned if Cancel button has been pressed
     */
    public static final int RET_CANCEL = 0;
    /**
     * A return status code - returned if OK button has been pressed
     */
    public static final int RET_OK = 1;
    private static UserInfo proprietario;
    private static Sessione sessione;
    private static SessioneApertaPanel pannello;
    private static UserInfo mittente;
    private static UserInfo destinatario;

    /**
     * Creates new form CaricaSoluzioneDialog
     */
    public CaricaSoluzioneDialog(java.awt.Frame parent, boolean modal, UserInfo proprietario, Sessione sessione, SessioneApertaPanel pannello, UserInfo mittente, UserInfo destinatario) {
        super(parent, modal);
        setLocationRelativeTo(parent);
        CaricaSoluzioneDialog.sessione = sessione;
        CaricaSoluzioneDialog.proprietario = proprietario;
        CaricaSoluzioneDialog.pannello = pannello;
        CaricaSoluzioneDialog.mittente = mittente;
        CaricaSoluzioneDialog.destinatario = destinatario;
        initComponents();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        caricaSoluzioneComboBox = new javax.swing.JComboBox();
        confermaCaricaButton = new javax.swing.JButton();
        annullaCaricaButton = new javax.swing.JButton();

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Seleziona una Soluzione da caricare");

        caricaSoluzioneComboBox.setModel(new javax.swing.DefaultComboBoxModel<Soluzione>());
        caricaSoluzioneComboBox.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                caricaSoluzioneComboBoxAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        confermaCaricaButton.setText("Conferma");
        confermaCaricaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confermaCaricaButtonActionPerformed(evt);
            }
        });

        annullaCaricaButton.setText("Annulla");
        annullaCaricaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                annullaCaricaButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(117, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(confermaCaricaButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(annullaCaricaButton))
                    .addComponent(caricaSoluzioneComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(114, 114, 114))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addGap(43, 43, 43)
                .addComponent(caricaSoluzioneComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confermaCaricaButton)
                    .addComponent(annullaCaricaButton))
                .addGap(50, 50, 50))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void confermaCaricaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confermaCaricaButtonActionPerformed

        // TODO add your handling code here:
        Soluzione s = (Soluzione) dlm.getSelectedItem();
        if (s != null) {
            sessionController.caricaSoluzione(sessione, s);
            pannello.segnalaSoluzioneCaricata();
        }
        doClose(RET_OK);

    }//GEN-LAST:event_confermaCaricaButtonActionPerformed

    private void annullaCaricaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_annullaCaricaButtonActionPerformed
        doClose(RET_CANCEL);
    }//GEN-LAST:event_annullaCaricaButtonActionPerformed

    private void caricaSoluzioneComboBoxAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_caricaSoluzioneComboBoxAncestorAdded
        try {
            List<Soluzione> soluzioni = sessionController.mostraSoluzioni(mittente, destinatario, proprietario);
            dlm = (DefaultComboBoxModel<Soluzione>) caricaSoluzioneComboBox.getModel();
            System.out.println("in dialog action");
            System.out.println("Caricate " + soluzioni.size() + "soluzioni");
            for (int i = 0; i < soluzioni.size(); i++) {
                Soluzione soluzione = soluzioni.get(i);
                dlm.addElement(soluzione);
            }
            caricaSoluzioneComboBox.setSelectedIndex(-1);
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_caricaSoluzioneComboBoxAncestorAdded

    private void caricaSoluzioneComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caricaSoluzioneComboBoxActionPerformed

    }//GEN-LAST:event_caricaSoluzioneComboBoxActionPerformed

    private void caricaSoluzioneComboBoxComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_caricaSoluzioneComboBoxComponentShown

    }//GEN-LAST:event_caricaSoluzioneComboBoxComponentShown

    private void doClose(int retStatus) {
        setVisible(false);
        dispose();
    }

    SessionController sessionController = SessionController.getInstance();
    private DefaultComboBoxModel<Soluzione> dlm;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton annullaCaricaButton;
    private javax.swing.JComboBox caricaSoluzioneComboBox;
    private javax.swing.JButton confermaCaricaButton;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
