/*
 * Copyright (C) 2014 glaxy
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package cryptohelper.view;

import cryptohelper.controller.GUIController;
import cryptohelper.model.Messaggio;
import cryptohelper.model.MessaggioDestinatario;
import cryptohelper.model.MessaggioMittente;
import cryptohelper.model.UserInfo;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;

/**
 *
 * @author glaxy
 */
public class messagePanel extends javax.swing.JPanel {

    /**
     * Creates new form messagePanel
     */
    public messagePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jTabbedPane2 = new javax.swing.JTabbedPane();
        messaggiRicevutiPanel = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        messaggiRicevutiList = new javax.swing.JList();
        jToolBar1 = new javax.swing.JToolBar();
        jButton3 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane9 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jButton10 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        messaggiInviatiPanel = new javax.swing.JPanel();
        jScrollPane11 = new javax.swing.JScrollPane();
        messaggiInviatiList = new javax.swing.JList();
        jPanel3 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jButton12 = new javax.swing.JButton();
        jScrollPane10 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        messaggiBozzePanel = new javax.swing.JPanel();
        jScrollPane12 = new javax.swing.JScrollPane();
        messaggiBozzaList = new javax.swing.JList();
        jPanel15 = new javax.swing.JPanel();
        jScrollPane13 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jPanel16 = new javax.swing.JPanel();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        messaggiCreaPanel = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();
        jTextField4 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        jPanel22 = new javax.swing.JPanel();
        jPanel21 = new javax.swing.JPanel();
        jButton8 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel23 = new javax.swing.JPanel();
        jPanel25 = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTextArea5 = new javax.swing.JTextArea();
        jPanel24 = new javax.swing.JPanel();
        jScrollPane14 = new javax.swing.JScrollPane();
        jTextArea6 = new javax.swing.JTextArea();

        messaggiRicevutiPanel.setLayout(new javax.swing.BoxLayout(messaggiRicevutiPanel, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel17.setLayout(new java.awt.BorderLayout());

        messaggiRicevutiList.setModel(new javax.swing.DefaultListModel<MessaggioDestinatario>());
        messaggiRicevutiList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        messaggiRicevutiList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                messaggiRicevutiListValueChanged(evt);
            }
        });
        messaggiRicevutiList.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                messaggiRicevutiListAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
                messaggiRicevutiListAncestorRemoved(evt);
            }
        });
        jScrollPane6.setViewportView(messaggiRicevutiList);

        jPanel17.add(jScrollPane6, java.awt.BorderLayout.CENTER);

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        jButton3.setText("Ricarica");
        jButton3.setFocusable(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton3);

        jPanel17.add(jToolBar1, java.awt.BorderLayout.PAGE_START);

        messaggiRicevutiPanel.add(jPanel17);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jTextArea1.setColumns(20);
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jScrollPane9.setViewportView(jTextArea1);

        jPanel2.add(jScrollPane9, java.awt.BorderLayout.CENTER);

        jButton10.setText("Elimina");
        jButton10.setEnabled(false);
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton10);

        jButton4.setText("Rispondi");
        jButton4.setEnabled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);

        jButton5.setText("Decifra");
        jButton5.setEnabled(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);

        jPanel2.add(jPanel1, java.awt.BorderLayout.PAGE_END);

        messaggiRicevutiPanel.add(jPanel2);

        jTabbedPane2.addTab("Ricevuti", messaggiRicevutiPanel);

        messaggiInviatiPanel.setLayout(new javax.swing.BoxLayout(messaggiInviatiPanel, javax.swing.BoxLayout.PAGE_AXIS));

        messaggiInviatiList.setModel(new javax.swing.DefaultListModel<MessaggioMittente>());
        messaggiInviatiList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        messaggiInviatiList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                messaggiInviatiListValueChanged(evt);
            }
        });
        messaggiInviatiList.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                messaggiInviatiListAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
                messaggiInviatiListAncestorRemoved(evt);
            }
        });
        jScrollPane11.setViewportView(messaggiInviatiList);

        messaggiInviatiPanel.add(jScrollPane11);

        jPanel3.setLayout(new java.awt.BorderLayout());

        jButton12.setText("Elimina");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton12);

        jPanel3.add(jPanel8, java.awt.BorderLayout.PAGE_END);

        jTextArea2.setColumns(20);
        jTextArea2.setLineWrap(true);
        jTextArea2.setRows(5);
        jScrollPane10.setViewportView(jTextArea2);

        jPanel3.add(jScrollPane10, java.awt.BorderLayout.CENTER);

        messaggiInviatiPanel.add(jPanel3);

        jTabbedPane2.addTab("Inviati", messaggiInviatiPanel);

        messaggiBozzePanel.setLayout(new javax.swing.BoxLayout(messaggiBozzePanel, javax.swing.BoxLayout.PAGE_AXIS));

        messaggiBozzaList.setModel(new javax.swing.DefaultListModel<MessaggioMittente>());
        messaggiBozzaList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        messaggiBozzaList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                messaggiBozzaListValueChanged(evt);
            }
        });
        messaggiBozzaList.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                messaggiBozzaListAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
                messaggiBozzaListAncestorRemoved(evt);
            }
        });
        jScrollPane12.setViewportView(messaggiBozzaList);

        messaggiBozzePanel.add(jScrollPane12);

        jPanel15.setLayout(new java.awt.BorderLayout());

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jScrollPane13.setViewportView(jTextArea3);

        jPanel15.add(jScrollPane13, java.awt.BorderLayout.CENTER);

        jButton14.setText("Componi");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        jPanel16.add(jButton14);

        jButton15.setText("Elimina");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        jPanel16.add(jButton15);

        jPanel15.add(jPanel16, java.awt.BorderLayout.PAGE_END);

        messaggiBozzePanel.add(jPanel15);

        jTabbedPane2.addTab("Bozze", messaggiBozzePanel);

        messaggiCreaPanel.setLayout(new javax.swing.BoxLayout(messaggiCreaPanel, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel19.setLayout(new java.awt.GridBagLayout());

        jTextField4.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 226;
        jPanel19.add(jTextField4, gridBagConstraints);

        jLabel7.setText("Destinatario:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        jPanel19.add(jLabel7, gridBagConstraints);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<UserInfo>());
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        jComboBox2.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jComboBox2AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
                jComboBox2AncestorRemoved(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 216;
        jPanel19.add(jComboBox2, gridBagConstraints);

        jLabel8.setText("Titolo:");
        jLabel8.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel19.add(jLabel8, gridBagConstraints);

        jLabel9.setText("Scegli un destinatario");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        jPanel19.add(jLabel9, gridBagConstraints);

        messaggiCreaPanel.add(jPanel19);

        jPanel18.setLayout(new java.awt.BorderLayout());

        jPanel22.setLayout(new javax.swing.BoxLayout(jPanel22, javax.swing.BoxLayout.PAGE_AXIS));
        jPanel18.add(jPanel22, java.awt.BorderLayout.PAGE_START);

        jButton8.setText("Cifra");
        jButton8.setEnabled(false);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel21.add(jButton8);

        jButton7.setText("Invia");
        jButton7.setEnabled(false);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel21.add(jButton7);

        jButton1.setText("Salva come Bozza");
        jButton1.setEnabled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel21.add(jButton1);

        jPanel18.add(jPanel21, java.awt.BorderLayout.PAGE_END);

        jPanel23.setLayout(new javax.swing.BoxLayout(jPanel23, javax.swing.BoxLayout.LINE_AXIS));

        jPanel25.setLayout(new java.awt.BorderLayout());

        jTextArea5.setColumns(20);
        jTextArea5.setRows(5);
        jTextArea5.setEnabled(false);
        jScrollPane8.setViewportView(jTextArea5);

        jPanel25.add(jScrollPane8, java.awt.BorderLayout.CENTER);

        jPanel23.add(jPanel25);

        jPanel24.setLayout(new java.awt.BorderLayout());

        jTextArea6.setEditable(false);
        jTextArea6.setColumns(20);
        jTextArea6.setLineWrap(true);
        jTextArea6.setRows(5);
        jTextArea6.setEnabled(false);
        jScrollPane14.setViewportView(jTextArea6);

        jPanel24.add(jScrollPane14, java.awt.BorderLayout.CENTER);

        jPanel23.add(jPanel24);

        jPanel18.add(jPanel23, java.awt.BorderLayout.CENTER);

        messaggiCreaPanel.add(jPanel18);

        jTabbedPane2.addTab("Crea Nuovo", messaggiCreaPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 568, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 568, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void messaggiRicevutiListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_messaggiRicevutiListValueChanged
        if (evt.getValueIsAdjusting() == false) {
            if (messaggiRicevutiList.getSelectedIndex() == -1) {
                jTextArea1.setText("");
                jButton10.setEnabled(false);
                jButton4.setEnabled(false);
                jButton5.setEnabled(false);
            } else {
                MessaggioDestinatario md = (MessaggioDestinatario) messaggiRicevutiList.getSelectedValue();
                jTextArea1.setText(md.getTestoCifrato());
                jButton10.setEnabled(true);
                jButton4.setEnabled(true);
                jButton5.setEnabled(true);
            }
        }
    }//GEN-LAST:event_messaggiRicevutiListValueChanged

    private void messaggiRicevutiListAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_messaggiRicevutiListAncestorAdded
        DefaultListModel<MessaggioDestinatario> dlm = (DefaultListModel<MessaggioDestinatario>) messaggiRicevutiList.getModel();
        List<MessaggioDestinatario> listaMessaggiRicevuti = null;
        try {
            listaMessaggiRicevuti = guiController.elencaMessaggiRicevuti();
        } catch (SQLException ex) {
            Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        for (MessaggioDestinatario m : listaMessaggiRicevuti) {
            dlm.addElement(m);
        }
    }//GEN-LAST:event_messaggiRicevutiListAncestorAdded

    private void messaggiRicevutiListAncestorRemoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_messaggiRicevutiListAncestorRemoved
        DefaultListModel<MessaggioDestinatario> dlm = (DefaultListModel<MessaggioDestinatario>) messaggiRicevutiList.getModel();
        dlm.clear();
    }//GEN-LAST:event_messaggiRicevutiListAncestorRemoved

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        DefaultListModel<MessaggioDestinatario> dlm = (DefaultListModel<MessaggioDestinatario>) messaggiRicevutiList.getModel();
        dlm.clear();
        List<MessaggioDestinatario> listaMessaggiRicevuti = null;
        try {
            listaMessaggiRicevuti = guiController.elencaMessaggiRicevuti();
        } catch (SQLException ex) {
            Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        for (MessaggioDestinatario m : listaMessaggiRicevuti) {
            dlm.addElement(m);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        try {
            Messaggio daCancellare = (Messaggio) messaggiRicevutiList.getSelectedValue();
            boolean b = guiController.eliminaMessaggioRicevuto(daCancellare);
            if (b == true) {
                DefaultListModel<MessaggioDestinatario> dlm = (DefaultListModel<MessaggioDestinatario>) messaggiRicevutiList.getModel();
                dlm.removeElement(daCancellare);
            }
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        idDestinatario = ((Messaggio) messaggiRicevutiList.getSelectedValue()).getMittente().getId();
        jTabbedPane2.setSelectedIndex(3);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        try {
            Messaggio oraLetto = (Messaggio) messaggiRicevutiList.getSelectedValue();
            int indiceLetto = messaggiRicevutiList.getSelectedIndex();
            guiController.decifraMessaggio(oraLetto);
            oraLetto.setLetto(true);
            oraLetto.save();
            jTextArea1.setText(oraLetto.getTesto());
            DefaultListModel<MessaggioDestinatario> dlm = (DefaultListModel<MessaggioDestinatario>) messaggiRicevutiList.getModel();
            dlm.set(indiceLetto, oraLetto);
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void messaggiInviatiListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_messaggiInviatiListValueChanged
        if (evt.getValueIsAdjusting() == false) {
            if (messaggiInviatiList.getSelectedIndex() == -1) {
                jTextArea2.setText("");
                jButton12.setEnabled(false);
            } else {
                MessaggioMittente md = (MessaggioMittente) messaggiInviatiList.getSelectedValue();
                jTextArea2.setText(md.getTesto());
                jButton12.setEnabled(true);
            }
        }
    }//GEN-LAST:event_messaggiInviatiListValueChanged

    private void messaggiInviatiListAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_messaggiInviatiListAncestorAdded
        DefaultListModel<MessaggioMittente> dlm = (DefaultListModel<MessaggioMittente>) messaggiInviatiList.getModel();
        List<MessaggioMittente> listaMessaggiInviati = null;
        try {
            listaMessaggiInviati = guiController.elencaMessaggiInviati();
        } catch (SQLException ex) {
            Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        for (MessaggioMittente m : listaMessaggiInviati) {
            dlm.addElement(m);
        }
    }//GEN-LAST:event_messaggiInviatiListAncestorAdded

    private void messaggiInviatiListAncestorRemoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_messaggiInviatiListAncestorRemoved
        DefaultListModel<MessaggioMittente> dlm = (DefaultListModel<MessaggioMittente>) messaggiInviatiList.getModel();
        dlm.clear();
    }//GEN-LAST:event_messaggiInviatiListAncestorRemoved

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        try {
            Messaggio daCancellare = (Messaggio) messaggiInviatiList.getSelectedValue();
            boolean b = guiController.eliminaMessaggioInviato(daCancellare);
            if (b == true) {
                DefaultListModel<MessaggioMittente> dlm = (DefaultListModel<MessaggioMittente>) messaggiInviatiList.getModel();
                dlm.removeElement(daCancellare);
            }
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_jButton12ActionPerformed

    private void messaggiBozzaListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_messaggiBozzaListValueChanged
        if (evt.getValueIsAdjusting() == false) {
            if (messaggiBozzaList.getSelectedIndex() == -1) {
                jTextArea3.setText("");
            } else {
                MessaggioMittente md = (MessaggioMittente) messaggiBozzaList.getSelectedValue();
                jTextArea3.setText(md.getTesto());
                jButton12.setEnabled(true);
            }
        }
    }//GEN-LAST:event_messaggiBozzaListValueChanged

    private void messaggiBozzaListAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_messaggiBozzaListAncestorAdded
        DefaultListModel<MessaggioMittente> dlm = (DefaultListModel<MessaggioMittente>) messaggiBozzaList.getModel();
        List<MessaggioMittente> listaBozze = null;
        try {
            listaBozze = guiController.elencaBozze();
        } catch (SQLException ex) {
            Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        for (MessaggioMittente m : listaBozze) {
            dlm.addElement(m);
        }
    }//GEN-LAST:event_messaggiBozzaListAncestorAdded

    private void messaggiBozzaListAncestorRemoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_messaggiBozzaListAncestorRemoved
        DefaultListModel<MessaggioMittente> dlm = (DefaultListModel<MessaggioMittente>) messaggiBozzaList.getModel();
        dlm.removeAllElements();
    }//GEN-LAST:event_messaggiBozzaListAncestorRemoved

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        idDestinatario = ((Messaggio) messaggiBozzaList.getSelectedValue()).getDestinatario().getId();
        titoloBozza = ((Messaggio) messaggiBozzaList.getSelectedValue()).getTitolo();
        testoBozza = jTextArea3.getText();
        jTabbedPane2.setSelectedIndex(3);
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        MessaggioMittente daCancellare = (Messaggio) messaggiBozzaList.getSelectedValue();
        DefaultListModel<MessaggioMittente> dlm = (DefaultListModel<MessaggioMittente>) messaggiBozzaList.getModel();
        try {
            boolean b = guiController.eliminaMessaggioBozza(daCancellare);
            if (b == true) {
                dlm.removeElement(daCancellare);
            }
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        UserInfo destinatario = (UserInfo) jComboBox2.getSelectedItem();
        if (destinatario != null) {
            String daCifrare = jTextArea6.getText();
            messaggio = guiController.creaMessaggio();
            messaggio.setDestinatario(destinatario);
            jLabel9.setText("Componi il messaggio e cifralo");
            jLabel8.setEnabled(true);
            jTextField4.setEnabled(true);
            jTextArea5.setEnabled(true);
            jTextArea6.setEnabled(true);
            jButton8.setEnabled(true);
            jButton1.setEnabled(true);
        }
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jComboBox2AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jComboBox2AncestorAdded
        DefaultComboBoxModel<UserInfo> dlm = (DefaultComboBoxModel<UserInfo>) jComboBox2.getModel();
        List<UserInfo> listaDestinatari = null;
        try {
            listaDestinatari = guiController.elencaDestinatari();
        } catch (SQLException ex) {
            Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        ActionListener[] myListeners = jComboBox2.getActionListeners();
        jComboBox2.removeActionListener(myListeners[0]);
        for (UserInfo ui : listaDestinatari) {
            dlm.addElement(ui);
        }
        if (idDestinatario != -1) {
            for (int i = 0; i < jComboBox2.getItemCount(); i++) {
                if (((UserInfo) jComboBox2.getItemAt(i)).getId() == idDestinatario) {
                    jComboBox2.setSelectedIndex(i);
                    jComboBox2ActionPerformed(null);
                    if (titoloBozza != null) {
                        jTextField4.setText(titoloBozza);
                        titoloBozza = null;
                    }
                    if (testoBozza != null) {
                        System.out.println("ciaoo");
                        jTextArea5.setText(testoBozza);
                        testoBozza = null;
                    }
                    idDestinatario = -1;
                }
            }
        } else {
            jComboBox2.setSelectedIndex(-1);
        }
        jComboBox2.addActionListener(myListeners[0]);
    }//GEN-LAST:event_jComboBox2AncestorAdded

    private void jComboBox2AncestorRemoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jComboBox2AncestorRemoved
        //salvaBozza(); //TODO
        setMessaggioEnabled(false);
        jLabel9.setText("Scegli un destinatario");
        DefaultComboBoxModel<UserInfo> dlm = (DefaultComboBoxModel<UserInfo>) jComboBox2.getModel();
        dlm.removeAllElements();
    }//GEN-LAST:event_jComboBox2AncestorRemoved

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        try {
            messaggio.setTesto(jTextArea5.getText());
            guiController.cifraMessaggio(messaggio);
            jTextArea6.setText(messaggio.getTestoCifrato());
            jLabel9.setText("Continua a comporre, oppure invia");
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
        jButton7.setEnabled(true);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        try {
            messaggio.setTitolo(jTextField4.getText());
            boolean b = guiController.spedisciMessaggio(messaggio);
            if (b == false) {
                jLabel9.setText("Errore nell'invio del messaggio!");
            } else {
                jLabel9.setText("Messaggio Inviato! Scegli un altro destinatario");
                setMessaggioEnabled(false);
            }
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            messaggio.setTitolo(jTextField4.getText());
            if (jTextArea5.getText().equals("")) {
                messaggio.setTesto("** testo vuoto **");
            }
            boolean b = guiController.salvaMessaggioBozza(messaggio);
            if (b == false) {
                jLabel9.setText("Errore nel salvataggio bozza!");
            } else {
                jLabel9.setText("Salvato come bozza!");
            }
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void setMessaggioEnabled(boolean b) {
        jLabel8.setEnabled(b);
        jTextField4.setEnabled(b);
        jTextArea5.setEnabled(b);
        jTextArea6.setEnabled(b);
        jButton1.setEnabled(b);
        jButton7.setEnabled(b);
        jButton8.setEnabled(b);
        jTextArea5.setText("");
        jTextArea6.setText("");
        jTextField4.setText("");
    }

    private final GUIController guiController = GUIController.getInstance();
    private Messaggio messaggio = null;
    private int idDestinatario = -1;
    private String titoloBozza = null;
    private String testoBozza = null;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea5;
    private javax.swing.JTextArea jTextArea6;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JList messaggiBozzaList;
    private javax.swing.JPanel messaggiBozzePanel;
    private javax.swing.JPanel messaggiCreaPanel;
    private javax.swing.JList messaggiInviatiList;
    private javax.swing.JPanel messaggiInviatiPanel;
    private javax.swing.JList messaggiRicevutiList;
    private javax.swing.JPanel messaggiRicevutiPanel;
    // End of variables declaration//GEN-END:variables
}
