/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cryptohelper.view;

import cryptohelper.controller.SessionController;
import cryptohelper.model.Soluzione;
import cryptohelper.model.Studente;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;

/**
 *
 * @author mat
 */
public class SoluzioniPanel extends javax.swing.JPanel {

    /**
     * Creates new form SoluzioniPanel
     *
     * @param st
     */
    public SoluzioniPanel(Studente st) {
        studente = st;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jButton1 = new javax.swing.JButton();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.PAGE_AXIS));

        jList1.setModel(new javax.swing.DefaultListModel<Soluzione>() {

        });
        jList1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jList1AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
                jList1AncestorRemoved(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane1.setViewportView(jList1);

        add(jScrollPane1);

        jButton1.setText("Elimina Soluzione");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.getAccessibleContext().setAccessibleName("EliminaButton");
    }// </editor-fold>//GEN-END:initComponents

    private void jList1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jList1AncestorAdded
        // TODO add your handling code here:
        try {
            dlm = (DefaultListModel<Soluzione>) jList1.getModel();
            List<Soluzione> soluzioni = sessionController.mostraSoluzioni(studente.getUserInfo());
            for (Soluzione soluzione : soluzioni) {
                dlm.addElement(soluzione);
            }
        } catch (SQLException ex) {
            Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jList1AncestorAdded

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Soluzione s = (Soluzione) jList1.getSelectedValue();
        try {
            sessionController.eliminaSoluzione(s);
            dlm.removeElement(s);
        } catch (SQLException ex) {
            System.out.println("Problema eliminazione: " + ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jList1AncestorRemoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jList1AncestorRemoved
        // TODO add your handling code here:
        dlm.clear();
    }//GEN-LAST:event_jList1AncestorRemoved

    private final Studente studente;
    SessionController sessionController = SessionController.getInstance();
    private DefaultListModel<Soluzione> dlm;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
